### ISSUE TITLE
CI: are we skipping unit tests in workflows?

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/kbs#298]
Maybe this got lost during a recent refactoring. I don't think we run the full-unit test suite as part of the CI currently. The tests are crucial, because they cover the cryptographic logic. Some of those tests are failing atm on main, e.g.: this is from the `verifier` project:

```bash
cargo t -p verifier --all-features
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
warning: skipping duplicate package `app` found at `/home/magnuskulke/.cargo/git/checkouts/sgxdatacenterattestationprimitives-d6934a418e6beae0/71557c7/SampleCode/RustSGXQuoteGenerationSample`
warning: skipping duplicate package `init` found at `/home/magnuskulke/.cargo/git/checkouts/occlum-09e22bc8c2a4bfe1/b5a32a8/demos/runtime_boot/init`
warning: skipping duplicate package `init` found at `/home/magnuskulke/.cargo/git/checkouts/occlum-09e22bc8c2a4bfe1/b5a32a8/tools/init`
   Compiling verifier v0.1.0 (/home/magnuskulke/dev/kbs/attestation-service/verifier)
    Finished test [unoptimized + debuginfo] target(s) in 8.92s
     Running unittests src/lib.rs (target/debug/deps/verifier-d7c94fb4fc7cb1f8)

running 62 tests
test az_snp_vtpm::tests::test_verify_report_data ... ok
test az_snp_vtpm::tests::test_verify_quote_akpub_failure ... ok
test cca::tests::test_cca_generate_parsed_claim ... FAILED
test az_snp_vtpm::tests::test_verify_report_data_failure ... ok
test sgx::tests::test_verify_sgx_quote::case_1 ... ignored
test sgx::claims::tests::parse_sgx_claims ... FAILED
test sgx::tests::test_parse_sgx_quote::case_1 ... ok
test az_snp_vtpm::tests::test_verify_quote_signature_failure ... ok
test snp::tests::check_milan_chain_signature_failure ... ok
test snp::tests::check_milan_certificates ... ok
test az_snp_vtpm::tests::test_verify_quote ... ok
test az_snp_vtpm::tests::test_verify_quote_nonce_failure ... ok
test snp::tests::check_vcek_parsing_legacy ... ok
test snp::tests::check_vcek_parsing ... ok
test snp::tests::check_vcek_parsing_new ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_01 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_02 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_03 ... ok
test snp::tests::check_vcek_signature_failure ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_04 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_05 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_06 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_07 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_08 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_09 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_10 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_11 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_12 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_13 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_14 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_15 ... ok
test snp::tests::check_vcek_signature_verification ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_16 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_17 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_18 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_19 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_20 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_21 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_22 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_24 ... ok
test az_snp_vtpm::tests::test_verify_snp_report ... ok
test tdx::claims::tests::test_td_shim_platform_config_info_try_from::case_01 ... ok
test tdx::claims::tests::test_td_shim_platform_config_info_try_from::case_02 ... ok
test tdx::claims::tests::test_parse_kernel_parameters::case_23 ... ok
test snp::tests::check_report_signature ... ok
test az_snp_vtpm::tests::test_verify_snp_report_failure ... ok
test tdx::claims::tests::test_td_shim_platform_config_info_try_from::case_03 ... ok
thread 'sgx::claims::tests::parse_sgx_claims' panicked at attestation-service/verifier/src/sgx/claims.rs:191:9:


json atom at path ".report_data" is missing from lhs

json atom at path ".init_data" is missing from lhs



---- tdx::claims::tests::parse_tdx_claims stdout ----
thread 'tdx::claims::tests::parse_tdx_claims' panicked at attestation-service/verifier/src/tdx/claims.rs:315:9:


json atom at path ".init_data" is missing from lhs

json atom at path ".quote.body.rtmr_2" is missing from lhs

json atom at path ".quote.body.rtmr_3" is missing from lhs

json atom at path ".quote.body.rtmr_1" is missing from lhs

json atom at path ".quote.body.rtmr_0" is missing from lhs

json atom at path ".report_data" is missing from lhs




failures:
    cca::tests::test_cca_generate_parsed_claim
    sgx::claims::tests::parse_sgx_claims
    tdx::claims::tests::parse_tdx_claims

test result: FAILED. 57 passed; 3 failed; 2 ignored; 0 measured; 0 filtered out; finished in 0.02s

error: test failed, to rerun pass `-p verifier --lib`
```

**Comment by Xynnn007** [comment]
Thanks for reporting this. Let me check inside.
